Install semver for version management in stage release workflow
Before It's not required to install semver specifically. But it suddenly returns following failure.
npm warn exec The following package was not found and will be installed: semver@7.7.1
Error: Process completed with exit code 1.